import more_itertools
# a=[['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT'], ['ASSORTED COLOUR BIRD ORNAMENT', "POPPY'S PLAYHOUSE BEDROOM ", "POPPY'S PLAYHOUSE KITCHEN", 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'IVORY KNITTED MUG COSY ', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE JIGSAW BLOCKS ', 'BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'RECIPE BOX WITH METAL HEART', 'DOORMAT NEW ENGLAND'], ['JAM MAKING SET WITH JARS', 'RED COAT RACK PARIS FASHION', 'YELLOW COAT RACK PARIS FASHION', 'BLUE COAT RACK PARIS FASHION'], ['BATH BUILDING BLOCK WORD'], ['ALARM CLOCK BAKELIKE PINK', 'ALARM CLOCK BAKELIKE RED ', 'ALARM CLOCK BAKELIKE GREEN', 'PANDA AND BUNNIES STICKER SHEET', 'STARS GIFT TAPE ', 'INFLATABLE POLITICAL GLOBE ', 'VINTAGE HEADS AND TAILS CARD GAME ', 'SET/2 RED RETROSPOT TEA TOWELS ', 'ROUND SNACK BOXES SET OF4 WOODLAND ', 'SPACEBOY LUNCH BOX ', 'LUNCH BOX I LOVE LONDON', 'CIRCUS PARADE LUNCH BOX ', 'CHARLOTTE BAG DOLLY GIRL DESIGN', 'RED TOADSTOOL LED NIGHT LIGHT', ' SET 2 TEA TOWELS I LOVE LONDON ', 'VINTAGE SEASIDE JIGSAW PUZZLES', 'MINI JIGSAW CIRCUS PARADE ', 'MINI JIGSAW SPACEBOY', 'MINI PAINT SET VINTAGE ', 'POSTAGE'], ["PAPER CHAIN KIT 50'S CHRISTMAS "], ['HAND WARMER RED POLKA DOT', 'HAND WARMER UNION JACK'], ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'EDWARDIAN PARASOL RED', 'RETRO COFFEE MUGS ASSORTED', 'SAVE THE PLANET MUG', 'VINTAGE BILLBOARD DRINK ME MUG', 'VINTAGE BILLBOARD LOVE/HATE MUG', 'WOOD 2 DRAWER CABINET WHITE FINISH', 'WOOD S/3 CABINET ANT WHITE FINISH', 'WOODEN PICTURE FRAME WHITE FINISH', 'WOODEN FRAME ANTIQUE WHITE ', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['VICTORIAN SEWING BOX LARGE'], ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER', 'EDWARDIAN PARASOL RED', 'RETRO COFFEE MUGS ASSORTED', 'SAVE THE PLANET MUG', 'VINTAGE BILLBOARD DRINK ME MUG', 'VINTAGE BILLBOARD LOVE/HATE MUG', 'WOOD 2 DRAWER CABINET WHITE FINISH', 'WOOD S/3 CABINET ANT WHITE FINISH', 'WOODEN PICTURE FRAME WHITE FINISH', 'WOODEN FRAME ANTIQUE WHITE ', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['HOT WATER BOTTLE TEA AND SYMPATHY', 'RED HANGING HEART T-LIGHT HOLDER'], ['HAND WARMER RED POLKA DOT', 'HAND WARMER UNION JACK'], ['JUMBO BAG PINK POLKADOT', 'JUMBO  BAG BAROQUE BLACK WHITE', 'JUMBO BAG CHARLIE AND LOLA TOYS', 'STRAWBERRY CHARLOTTE BAG', 'RED 3 PIECE RETROSPOT CUTLERY SET', 'BLUE 3 PIECE POLKADOT CUTLERY SET', 'SET/6 RED SPOTTY PAPER PLATES', 'LUNCH BAG RED RETROSPOT', 'STRAWBERRY LUNCH BOX WITH CUTLERY', 'LUNCH BOX WITH CUTLERY RETROSPOT ', 'PACK OF 72 RETROSPOT CAKE CASES', 'PACK OF 60 DINOSAUR CAKE CASES', 'PACK OF 60 PINK PAISLEY CAKE CASES', '60 TEATIME FAIRY CAKE CASES', 'TOMATO CHARLIE+LOLA COASTER SET', 'CHARLIE & LOLA WASTEPAPER BIN FLORA', 'RED CHARLIE+LOLA PERSONAL DOORSIGN', 'JUMBO STORAGE BAG SUKI', 'JUMBO BAG PINK VINTAGE PAISLEY'], ['JAM MAKING SET PRINTED'], ['RETROSPOT TEA SET CERAMIC 11 PC ', 'GIRLY PINK TOOL SET', 'JUMBO SHOPPER VINTAGE RED PAISLEY', 'AIRLINE LOUNGE,METAL SIGN', 'WHITE SPOT RED CERAMIC DRAWER KNOB', 'RED DRAWER KNOB ACRYLIC EDWARDIAN', 'CLEAR DRAWER KNOB ACRYLIC EDWARDIAN', 'PHOTO CLIP LINE', 'FELT EGG COSY CHICKEN', 'PIGGY BANK RETROSPOT ', 'SKULL SHOULDER BAG', "YOU'RE CONFUSING ME METAL SIGN ", 'COOK WITH WINE METAL SIGN ', 'GIN + TONIC DIET METAL SIGN', 'YELLOW BREAKFAST CUP AND SAUCER', 'PINK BREAKFAST CUP AND SAUCER ', "PAPER CHAIN KIT 50'S CHRISTMAS ", 'PAPER CHAIN KIT RETROSPOT', 'SMALL HEART FLOWERS HOOK ', 'PHOTO CLIP LINE', 'TEA TIME DES TEA COSY', 'FELT EGG COSY WHITE RABBIT ', 'ZINC WILLIE WINKIE  CANDLE STICK', 'CERAMIC CHERRY CAKE MONEY BANK', 'RETROSPOT LARGE MILK JUG', 'SET OF 6 FUNKY BEAKERS', 'EDWARDIAN PARASOL BLACK', 'EDWARDIAN PARASOL NATURAL', 'CERAMIC STRAWBERRY CAKE MONEY BANK', 'BLUE OWL SOFT TOY', 'BALLOON ART MAKE YOUR OWN FLOWERS', 'RED TOADSTOOL LED NIGHT LIGHT', 'GLASS CLOCHE SMALL', 'GUMBALL MONOCHROME COAT RACK', 'DOORMAT FANCY FONT HOME SWEET HOME'], ['Discount'], ['INFLATABLE POLITICAL GLOBE ', 'VINTAGE SNAKES & LADDERS', 'CHOCOLATE CALCULATOR', 'JUMBO SHOPPER VINTAGE RED PAISLEY', 'RECYCLING BAG RETROSPOT ', 'TOY TIDY PINK POLKADOT', 'ANTIQUE GLASS DRESSING TABLE POT', 'ALARM CLOCK BAKELIKE GREEN', 'IVORY GIANT GARDEN THERMOMETER', '3 TIER CAKE TIN GREEN AND CREAM', '3 TIER CAKE TIN RED AND CREAM', 'SET 3 WICKER OVAL BASKETS W LIDS'], ['SET OF 3 COLOURED  FLYING DUCKS'], ['WOOD BLACK BOARD ANT WHITE FINISH', 'COLOUR GLASS T-LIGHT HOLDER HANGING', 'HANGING METAL HEART LANTERN', 'HANGING MEDINA LANTERN SMALL', 'NATURAL SLATE HEART CHALKBOARD ', 'HEART OF WICKER SMALL', 'HEART OF WICKER LARGE', 'WHITE LOVEBIRD LANTERN', 'CLASSIC METAL BIRDCAGE PLANT HOLDER', 'CREAM HEART CARD HOLDER', 'ENAMEL FLOWER JUG CREAM', 'ENAMEL FIRE BUCKET CREAM', 'ENAMEL BREAD BIN CREAM'], ['SET 3 WICKER OVAL BASKETS W LIDS', 'JAM MAKING SET PRINTED', 'JAM MAKING SET WITH JARS', 'JUMBO BAG DOLLY GIRL DESIGN', 'TRADITIONAL CHRISTMAS RIBBONS', 'ORGANISER WOOD ANTIQUE WHITE ', 'LUNCH BAG DOLLY GIRL DESIGN'], ['WHITE WIRE EGG HOLDER', 'JUMBO  BAG BAROQUE BLACK WHITE', 'JUMBO BAG RED RETROSPOT'], ['CHILLI LIGHTS', 'LIGHT GARLAND BUTTERFILES PINK', 'WOODEN OWLS LIGHT GARLAND ', 'FAIRY TALE COTTAGE NIGHTLIGHT', 'RED TOADSTOOL LED NIGHT LIGHT'], ['HOME BUILDING BLOCK WORD', 'LOVE BUILDING BLOCK WORD', 'DOORMAT FANCY FONT HOME SWEET HOME', 'HOME SMALL WOOD LETTERS', 'GINGHAM HEART  DOORSTOP RED', 'FIVE HEART HANGING DECORATION', 'HANGING METAL HEART LANTERN', 'ASSORTED BOTTLE TOP  MAGNETS ', 'FRIDGE MAGNETS US DINER ASSORTED', 'HOMEMADE JAM SCENTED CANDLES', 'FRIDGE MAGNETS LES ENFANTS ASSORTED', 'ROSE CARAVAN DOORSTOP', 'HEART OF WICKER SMALL', '5 HOOK HANGER MAGIC TOADSTOOL'], ['CHRISTMAS LIGHTS 10 REINDEER', 'VINTAGE UNION JACK CUSHION COVER', 'VINTAGE HEADS AND TAILS CARD GAME ']]
# b= [['WHITE METAL LANTERN', 'RED WOOLLY HOTTIE WHITE HEART.'], ['WHITE METAL LANTERN', 'HAND WARMER UNION JACK'], ['WHITE METAL LANTERN', 'CREAM CUPID HEARTS COAT HANGER'], ['WHITE METAL LANTERN', 'SET 7 BABUSHKA NESTING BOXES'], ['WHITE METAL LANTERN', 'HAND WARMER RED POLKA DOT'], ['WHITE METAL LANTERN', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['WHITE METAL LANTERN', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['WHITE METAL LANTERN', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['WHITE METAL LANTERN', 'RED TOADSTOOL LED NIGHT LIGHT'], ['RED WOOLLY HOTTIE WHITE HEART.', 'HAND WARMER UNION JACK'], ['RED WOOLLY HOTTIE WHITE HEART.', 'CREAM CUPID HEARTS COAT HANGER'], ['RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES'], ['RED WOOLLY HOTTIE WHITE HEART.', 'HAND WARMER RED POLKA DOT'], ['RED WOOLLY HOTTIE WHITE HEART.', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['RED WOOLLY HOTTIE WHITE HEART.', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['RED WOOLLY HOTTIE WHITE HEART.', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['RED WOOLLY HOTTIE WHITE HEART.', 'RED TOADSTOOL LED NIGHT LIGHT'], ['HAND WARMER UNION JACK', 'CREAM CUPID HEARTS COAT HANGER'], ['HAND WARMER UNION JACK', 'SET 7 BABUSHKA NESTING BOXES'], ['HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT'], ['HAND WARMER UNION JACK', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['HAND WARMER UNION JACK', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['HAND WARMER UNION JACK', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['HAND WARMER UNION JACK', 'RED TOADSTOOL LED NIGHT LIGHT'], ['CREAM CUPID HEARTS COAT HANGER', 'SET 7 BABUSHKA NESTING BOXES'], ['CREAM CUPID HEARTS COAT HANGER', 'HAND WARMER RED POLKA DOT'], ['CREAM CUPID HEARTS COAT HANGER', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['CREAM CUPID HEARTS COAT HANGER', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['CREAM CUPID HEARTS COAT HANGER', 'RED TOADSTOOL LED NIGHT LIGHT'], ['SET 7 BABUSHKA NESTING BOXES', 'HAND WARMER RED POLKA DOT'], ['SET 7 BABUSHKA NESTING BOXES', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['SET 7 BABUSHKA NESTING BOXES', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['SET 7 BABUSHKA NESTING BOXES', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['SET 7 BABUSHKA NESTING BOXES', 'RED TOADSTOOL LED NIGHT LIGHT'], ['HAND WARMER RED POLKA DOT', 'GLASS STAR FROSTED T-LIGHT HOLDER'], ['HAND WARMER RED POLKA DOT', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['HAND WARMER RED POLKA DOT', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['HAND WARMER RED POLKA DOT', 'RED TOADSTOOL LED NIGHT LIGHT'], ['GLASS STAR FROSTED T-LIGHT HOLDER', 'WHITE HANGING HEART T-LIGHT HOLDER'], ['GLASS STAR FROSTED T-LIGHT HOLDER', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['GLASS STAR FROSTED T-LIGHT HOLDER', 'RED TOADSTOOL LED NIGHT LIGHT'], ['WHITE HANGING HEART T-LIGHT HOLDER', 'KNITTED UNION FLAG HOT WATER BOTTLE'], ['WHITE HANGING HEART T-LIGHT HOLDER', 'RED TOADSTOOL LED NIGHT LIGHT'], ['KNITTED UNION FLAG HOT WATER BOTTLE', 'RED TOADSTOOL LED NIGHT LIGHT']]
# print(len(a))
# print(len(b))
# dem1 =0
# for j in b:
#     # print(j)
#     dem1 +=1
# print(dem1)
# dem=0
#
# l = []
# for i in range(len(b)):
#     l.append(i)
# dic_item = dict.fromkeys(l, 0)
#
# for i in a:
#     for item in b:
#         if all(itemm in i for itemm in item):
#             dic_item[b.index(item)] += 1
# print(dic_item)
# ressult = []
# for i in dic_item: # remove itemset have min_supported < self.support
#     if dic_item[i] >= 3:
#         ressult.append(b[i])
# print(len(ressult), ressult)
# from datetime import datetime
# a = datetime.now().time()
# b = datetime.now().time()
# # print(str(a)-str(b))
# print(a)
# def time(s1, s2):
#     s1,s2 = str(s1), str(s2)
#     hour1=s1[0:2]
#     hour2 = s2[0:2]
#     min1 = s1[3:5]
#     min2 = s2[3:5]
#     second1= s1[6:8]
#     second2 = s2[6:8]
#     return (hour2 - hour1) * 3600 + (min2 - min1) * 60 + (second2-second1)
# print(time(str(a),str(b)))
# a=['a']
# b=['b','c']
# c=[]
# c.append([a,b])
# c.append([a,b])
# print(c)
# k=[]
# m=[]
temp =[]
def confident_suppored_itemset(left, right):  # XY la 1 supported_itemset.
    result(left, right)
    if len(left) == 1:
        pass
    else:
        for i in more_itertools.distinct_combinations(left, 1):
            print(list(i)[0])
            x,y=left.copy(),right.copy()
            y.append(list(i)[0])
            x.remove(list(i)[0])
            # print(y)
            # print(list(i)[0])
            # print("X:", x)
            # print("Y:", y)
            l= [x,y]
            print("XY: ",l)
            confident_suppored_itemset(x,y)
def result(left, right):
    if len(right)>0:
        if left not in temp:
            re.append([left,right])
            temp.append(left)

# def confident_suppored_itemset(left, right):  # left: ['A', 'B', 'C', 'D']
#     print("l: ", left)
#     print("r: ", right)
#     stx.pop(0)
#     sty.pop(0)
#     for i in more_itertools.distinct_combinations(left, 1):
#         print("list(i)[0]",list(i)[0])
#         x = left.copy()
#         y = right.copy()
#         y.append(list(i)[0])
#         x.remove(list(i)[0])
#         print(y)
#         print(list(i)[0])
#         print("X:", x)
#         print("Y:", y)
#         l = [x, y]
#         print("XY: ", l)
#         if len(x) > 1 :
#             stx.append(x)
#             sty.append(y)
#     confident_suppored_itemset(stx[0],sty[0])
def gen_rule(x, y):
    re.append([x,y])
    confident_suppored_itemset(x,y)
X=['A','B','C','D']
Y=[]
re=[]
stx=[]
sty = []
stx.append(X)
sty.append(Y)
# confident_suppored_itemset(stx[0],sty[0])
confident_suppored_itemset(X,Y)
print("Result ",re)
print(len(re))

a=['a','b']
b=['c','l']
c= []
c.extend(a)
c.extend(b)
print("djfhd", c)
